apiVersion: v1
kind: Service
metadata:
  name: recipe-api
spec:
  selector:
    app: recipeapi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8090
      nodePort: 31001
  type: NodePort